const lightCodeTheme = require('prism-react-renderer').themes.github;
const darkCodeTheme = require('prism-react-renderer').themes.dracula;

import remarkFindReplacePlugin from './src/plugins/remarkFindReplacePlugin.mjs';
import remarkSimplePlantumlPlugin from './src/plugins/remarkSimplePlantumlPlugin.mjs';
import plantumlRenderPlugin from './src/plugins/plantumlRenderPlugin.mjs';
import scalarApiPlugin from './src/plugins/scalarApiPlugin.mjs';
import {apiCatalog} from './src/data/apiCatalog.mjs';
import {resolveApiCatalog, buildApiNavbarItems} from './src/lib/apiCatalog.mjs';
import {
  apiVersion,
  chartVersion,
  cscVersion,
  operatorVersion,
  cliVersion,
  operatorDocsRef,
  cliDocsRef,
  devenvDocsRef,
} from './src/data/versions.mjs';

// Routes and navbar menus for all published APIs come from src/data/apiCatalog.mjs.
const apiNavbarItems = buildApiNavbarItems(resolveApiCatalog(apiCatalog, {apiVersion, cscVersion}));


/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'ILM Documentation',
  tagline: 'Security and trust assurance and automation in ever connected world',
  url: 'https://docs.otilm.com',
  baseUrl: '/',
  onBrokenLinks: 'throw',
  favicon: 'img/ot-sign-color.svg',
  organizationName: 'OmniTrustILM', // Usually your GitHub org/user name.
  projectName: 'documentation', // Usually your repo name.
  trailingSlash: false,

  markdown: {
    mdx1Compat: {
      comments: false,
      admonitions: false,
      headingIds: false,
    },
    hooks: {
      // 'throw', not 'warn': the synced sets (see CLAUDE.md) may only use same-directory
      // relative links, and a warning nobody reads is how a broken link reaches production.
      onBrokenMarkdownLinks: 'throw',
    },
  },

  // plugins: [
  //     './src/plugins/test'
  // ],
  plugins: [
    plantumlRenderPlugin,
    [scalarApiPlugin, {apiVersion, cscVersion}],
    [
      "docusaurus-plugin-remote-content",
      {
        // options here
        name: "helm-docs", // used by CLI, must be path safe
        noRuntimeDownloads: true, // disable runtime downloads, use only CLI to download (docusaurus download-remote-helm-docs)
        performCleanup: false, // do not remove downloaded files on build
        sourceBaseUrl: "https://raw.githubusercontent.com/OmniTrustILM/helm-charts/"+chartVersion+"/charts/ilm/docs/", // the base url for the markdown (gets prepended to all of the documents when fetching)
        outDir: "docs/certificate-key/installation-guide/deployment/deployment-helm", // the base directory to output to.
        documents: ["configurable-parameters.md", "overview.md", "troubleshooting.md", "upgrading.md"], // the file names to download
      },
    ],
    [
      "docusaurus-plugin-remote-content",
      {
        // Authored in OmniTrustILM/operator under docs/site/. Files written here are
        // OVERWRITTEN by the next download — fix errors upstream, never here.
        name: "operator-docs",
        noRuntimeDownloads: true,
        performCleanup: false,
        sourceBaseUrl: "https://raw.githubusercontent.com/OmniTrustILM/operator/" + operatorDocsRef + "/docs/site/",
        outDir: "docs/certificate-key/installation-guide/deployment/deployment-operator",
        // The five journey pages, in sidebar_position order. The four CR guides live in
        // the custom-resources/ subdirectory and are synced by the entry below.
        documents: ["overview.md", "installation.md", "upgrading.md", "migration-from-helm.md", "troubleshooting.md"],
      },
    ],
    [
      "docusaurus-plugin-remote-content",
      {
        // Authored in OmniTrustILM/operator under docs/site/custom-resources/ — the four
        // CR guides, grouped on the site under the "Custom Resources" sidebar category
        // (the category file is site-owned). Same ref as operator-docs; both entries are
        // re-pinned together. Files written here are OVERWRITTEN by the next download.
        name: "operator-cr-docs",
        noRuntimeDownloads: true,
        performCleanup: false,
        sourceBaseUrl: "https://raw.githubusercontent.com/OmniTrustILM/operator/" + operatorDocsRef + "/docs/site/custom-resources/",
        outDir: "docs/certificate-key/installation-guide/deployment/deployment-operator/custom-resources",
        documents: ["platform.md", "platform-options.md", "connector.md", "proxy.md"],
      },
    ],
    [
      "docusaurus-plugin-remote-content",
      {
        // Authored in OmniTrustILM/cli under docs/site/. commands.md is generated by
        // `make docs` there. Files written here are OVERWRITTEN by the next download.
        name: "cli-docs",
        noRuntimeDownloads: true,
        performCleanup: false,
        sourceBaseUrl: "https://raw.githubusercontent.com/OmniTrustILM/cli/" + cliDocsRef + "/docs/site/",
        outDir: "docs/certificate-key/cli",
        documents: ["index.md", "quickstart.md", "configuration.md", "gitops.md", "upgrades.md", "troubleshooting.md", "diagnostics.md", "commands.md"],
      },
    ],
    [
      "docusaurus-plugin-remote-content",
      {
        // Authored in OmniTrustILM/development-environment under docs/site/.
        // Files written here are OVERWRITTEN by the next download.
        name: "devenv-docs",
        noRuntimeDownloads: true,
        performCleanup: false,
        sourceBaseUrl: "https://raw.githubusercontent.com/OmniTrustILM/development-environment/" + devenvDocsRef + "/docs/site/",
        outDir: "docs/contributors",
        documents: ["development-environment.md"],
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'problems',
        path: 'problems',
        routeBasePath: 'problems',
        sidebarPath: require.resolve('./sidebarProblems.js'),
      },
    ],
    [
      '@docusaurus/plugin-client-redirects',
      {
        redirects: [
          {
            to: '/docs',
            from: '/test',
          },
          { to: '/docs/certificate-key/integration-guides/cert-manager-issuer/create-issuer', from: '/docs/certificate-key/integration-guides/cert-manager-issuer/create-czertainly-issuer' },
          { to: '/docs/certificate-key/integration-guides/cert-manager-issuer/install-issuer', from: '/docs/certificate-key/integration-guides/cert-manager-issuer/install-czertainly-issuer' },
          { to: '/docs/certificate-key/integration-guides/adfs/configure-ilm', from: '/docs/certificate-key/integration-guides/adfs/configure-czertainly' },
          { to: '/docs/certificate-key/integration-guides/intune/authorize-ilm', from: '/docs/certificate-key/integration-guides/intune/authorize-czertainly' },
          { to: '/docs/certificate-key/integration-guides/keycloak/theme', from: '/docs/certificate-key/integration-guides/keycloak/czertainly-theme' },
        ],
        createRedirects: function (existingPath) {
          // do not redirect root
          if (existingPath === '/') {
            return undefined;
          }
          // SignServer (legacy) docs moved from /docs/signing/* to /docs/signserver/*.
          // For each new /docs/signserver/* route, register its old /docs/signing/* path
          // as a redirect source — EXCEPT 'introduction', whose old path is now the live
          // native signing landing page (a redirect there would collide and be wrong).
          if (existingPath.startsWith('/docs/signserver/')) {
            const oldPath = existingPath.replace('/docs/signserver/', '/docs/signing/');
            if (oldPath === '/docs/signing/introduction') {
              return undefined;
            }
            return oldPath;
          }
          if (existingPath.endsWith('/')) {
            // remove the trailing slash and redirect
            return existingPath.slice(0, -1);
          }
          return undefined; // Return a falsy value: no redirect created
        },
      },
    ]
  ],
  presets: [
    [
      '@docusaurus/preset-classic',
      ({
        docs: {
          showLastUpdateAuthor: true,
          showLastUpdateTime: true,
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl: ({versionDocsDirPath, docPath}) =>
              `https://github.com/OmniTrustILM/documentation/edit/documentation/${versionDocsDirPath}/${docPath}`,
          remarkPlugins: [
            [
              remarkFindReplacePlugin,
              {
                // List your find and replace values. Both values must be strings.
                // This is required.
                replacements: {
                  API_BASE_URL: 'https://docs.otilm.com/api/',
                  OPERATOR_VERSION: operatorVersion,
                  CLI_VERSION: cliVersion,
                },
                // By default, find values are prefixed to reduce the chances of
                // conflicting with real content. You can change the prefix here.
                // Set to `false` to disable the prefix.
                prefix: '%'
              },
            ],
            remarkSimplePlantumlPlugin,
          ],
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  themeConfig:
  /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
      ({
        docs: {
          sidebar: {
            hideable: true,
          },
        },
        navbar: {
          title: 'ILM Documentation',
          logo: {
            alt: 'ILM Logo',
            src: 'img/ot-sign-color.svg',
            srcDark: 'img/ot-sign-white.svg',
          },
          items: [
            // {
            //   type: 'doc',
            //   docId: 'intro',
            //   position: 'left',
            //   label: 'Tutorial',
            // },
            // {to: '/blog', label: 'Blog', position: 'left'},
            {
              label: 'Docs',
              position: 'left',
              to: '/docs',
            },
            ...apiNavbarItems,
            {
              href: 'https://github.com/OmniTrustILM/ilm/discussions',
              className: 'pseudo-icon github-icon',
              position: 'right',
            },
            {
              href: 'https://discord.gg/XYsSZKjSt4',
              className: 'pseudo-icon discord-icon',
              position: 'right',
            },
            {
              href: 'https://securedbyintegrity.com/platform/identity-lifecycle-management-ilm/',
              label: 'About ILM',
              position: 'right',
            },
          ],
        },
        footer: {
          style: 'dark',
          // links: [
          //   {
          //     title: 'Docs',
          //     items: [
          //       {
          //         label: 'Tutorial',
          //         to: '/docs/intro',
          //       },
          //     ],
          //   },
          //   {
          //     title: 'Community',
          //     items: [
          //       {
          //         label: 'Stack Overflow',
          //         href: 'https://stackoverflow.com/questions/tagged/docusaurus',
          //       },
          //       {
          //         label: 'Discord',
          //         href: 'https://discordapp.com/invite/docusaurus',
          //       },
          //       {
          //         label: 'Twitter',
          //         href: 'https://twitter.com/docusaurus',
          //       },
          //     ],
          //   },
          //   {
          //     title: 'More',
          //     items: [
          //       {
          //         label: 'Blog',
          //         to: '/blog',
          //       },
          //       {
          //         label: 'GitHub',
          //         href: 'https://github.com/facebook/docusaurus',
          //       },
          //     ],
          //   },
          // ],
          copyright: `Copyright © 2018 - ${new Date().getFullYear()} Identity Lifecycle Management Built with Docusaurus`,
        },
        prism: {
          theme: lightCodeTheme,
          darkTheme: darkCodeTheme,
          additionalLanguages: ['powershell','java','hcl','scala','bash'],
        },
        algolia: {
          // The application ID provided by Algolia
          appId: '9LVBEQBLSX',
          // Public API key: it is safe to commit it
          apiKey: 'e5c6094c457339acfcd8114bef0f509a',
          indexName: 'ilm',
          // Optional: see doc section below
          contextualSearch: true,
        },
      }),
};

export default config;
