name: Documentation

on:
  pull_request:
    branches: [documentation]
  push:
    branches: [documentation]

jobs:
  checks:
    if: github.event_name != 'push'
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.x
      - name: Set up PlantUML rendering
        uses: ./.github/actions/plantuml
      - name: Test build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn verify-api-build
  gh-release:
    if: github.event_name != 'pull_request'
    name: Deploy to GitHub Pages

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.x
      - name: Set up PlantUML rendering
        uses: ./.github/actions/plantuml
      - name: Build website
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn verify-api-build
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
